#Global Settings & Data Sources

# Global Currency
# if we use Money Libraries like  moneyphp/money, brick/money
currency: 'USD'
is_logging: true

# Data Sources products
products:
  R01:
    name: Red Widget
    price: 32.95
  G01:
    name: Green Widget
    price: 24.95
  B01:
    name: Blue Widget
    price: 7.95

# Data Sources Delivery Rules
delivery_rules:
  - threshold: 50
    cost: 4.95
  - threshold: 90
    cost: 2.95
  - threshold: PHP_FLOAT_MAX
    cost: 0.0

# Data Sources Offers
offers:
  - productCode: R01
    quantity: 2
    discount: 16.475
